project_id = "mozqijzvtbuwuzgemzsm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://madeai.com.br"
additional_redirect_urls = ["https://madeai.com.br", "https://madeai.com.br/auth/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.hook.send_email]
enabled = true
uri = "https://mozqijzvtbuwuzgemzsm.supabase.co/functions/v1/auth-email-webhook"

[db]
port = 54322

[functions.upload-project]
verify_jwt = false

[functions.migrate-projects]
verify_jwt = false

[functions.webhook-automation]
verify_jwt = false

[functions.bulk-email-sender]
verify_jwt = false

[functions.admin-impersonate]
verify_jwt = true

[functions.admin-end-impersonation]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false

[functions.ip-geolocation]
verify_jwt = false

[functions.secure-n8n-proxy]
verify_jwt = true

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54325
inspector_port = 5432

[functions.send-custom-emails]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.auth-email-webhook]
verify_jwt = false

[analytics]
enabled = false